name: Auto Update Nico Comment

on:
  schedule:
    - cron: '*/1 * * * *'  # 1分ごとに実行（UTC）

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Call /update endpoint
        run: curl -s https://nico-comment-backend-api-production.up.railway.app/update
